### ISSUE TITLE
What is `X` supposed to be in `riemannian_Hessian`?

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaManifolds/ManifoldDiff.jl#42]
Here https://github.com/JuliaManifolds/ManifoldDiff.jl/blob/96b0b0b9bbd6c27cbb354b962b56a6881257fc3b/src/riemannian_diff.jl#L358 I am not sure what the X needs to be initialized as?

**Comment by kellertuer** [comment]
On the manifold M at a point p, X is a tangent vector to p.
WE do not implement Hessians as a matrix (because that is hard to do when most representations are a bit larger than the manifold dimension), but We write Hessians as how they act on a incoming derivative direction. See also Definition 5.14 in https://www.nicolasboumal.net/book/IntroOptimManifolds_Boumal_2023.pdf (p. 95).
Of course Y is the in-place variant (also a tangent vector) for the result.
